### ISSUE TITLE
Blue links do not go well with the darker color schemes

### ISSUE THREAD

**Issue by geek1011** [geek1011/BookReader#6]
Blue links on the darker color schemes clash with the background. They should be changed to inherit the color, and be underlined

**Comment by geek1011** [comment]
This should be done with a hook on displayChapter to add the following css to an appended style tag in the body.

````css
a:link, a:visited {
    color: inherit !important;
    text-decoration: underline !important;
}
````
